fixed deployement artifact location issue (#3)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -67,6 +67,13 @@ jobs:
           username: ${{ secrets.VPS_USER }}
           key: ${{ secrets.VPS_SSH_KEY }}
           script: |
+            cd /home/${{ secrets.VPS_USER }}
+            echo "Checking files..."
+            ls -lh
+            if [ ! -f myapp.tar ]; then
+              echo "ERROR: myapp.tar not found!"
+              exit 1
+            fi
             docker load < myapp.tar
             docker stop myapp || true
             docker rm myapp || true
